package javaforce.tests;

import java.awt.*;
import java.awt.dnd.*;
import java.awt.datatransfer.*;

import javaforce.*;
import javaforce.awt.*;

/**
 * TestAWT
 *
 * @author pquiring
 */
public class TestAWT extends java.awt.Frame {

  /**
   * Creates new form TestAWT
   */
  public TestAWT() {
    initComponents();
    DragSource.getDefaultDragSource().createDefaultDragGestureRecognizer(drag_me, DnDConstants.ACTION_COPY_OR_MOVE,
      e -> {
        Transferable transferable = new StringSelection("Dropped Text");
        e.startDrag(DragSource.DefaultCopyDrop, transferable, null);
      }
    );
    new DropTarget(drop_area, DnDConstants.ACTION_COPY_OR_MOVE,
      new DropTargetAdapter() {
      public void drop(DropTargetDropEvent evt) {
        try {
          evt.acceptDrop(DnDConstants.ACTION_COPY);
          Transferable tr = evt.getTransferable();
          if (tr.isDataFlavorSupported(DataFlavor.stringFlavor)) {
            String data = (String) tr.getTransferData(DataFlavor.stringFlavor);
            drop_area.setText(data);
            evt.dropComplete(true);
          } else {
            evt.rejectDrop();
          }
        } catch (Exception ex) {
          evt.dropComplete(false);
        }
      }
    }
    );
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
   * Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    button1 = new java.awt.Button();
    textField1 = new java.awt.TextField();
    drag_me = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    drop_area = new javax.swing.JTextArea();

    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        exitForm(evt);
      }
    });

    button1.setLabel("button1");
    button1.addActionListener(this::button1ActionPerformed);

    textField1.setText("textField1");

    drag_me.setText("Drag Me");

    drop_area.setColumns(20);
    drop_area.setRows(5);
    drop_area.setText("Drop Here");
    jScrollPane1.setViewportView(drop_area);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(drag_me)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1))
          .addGroup(layout.createSequentialGroup()
            .addComponent(textField1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(textField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(drag_me)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * Exit the Application
   */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
      System.exit(0);
    }//GEN-LAST:event_exitForm

  private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
    test();
  }//GEN-LAST:event_button1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TestAWT().setVisible(true);
      }
    });
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private java.awt.Button button1;
  private javax.swing.JLabel drag_me;
  private javax.swing.JTextArea drop_area;
  private javax.swing.JScrollPane jScrollPane1;
  private java.awt.TextField textField1;
  // End of variables declaration//GEN-END:variables

  private void test() {
    System.out.println("button clicked!");
  }
}
