/** Logon.
 *
 * Created : Mar 31, 2012
 *
 * @author pquiring
 */

import java.awt.event.*;
import java.io.*;
import java.util.*;

import javax.swing.Icon;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

import javaforce.*;
import javaforce.awt.*;
import javaforce.linux.*;
import javaforce.api.linux.*;
import javaforce.bus.*;
import javaforce.net.*;

public class Logon extends javax.swing.JFrame implements ActionListener {

  private static Properties props;
  private static boolean is_wayland = false;

  private static int LOG_DEFAULT = 0;

  private static void load_config() {
    props = Linux.getJFLinuxProperties();
    is_wayland = getProperty("wayland").equals("true");
  }

  /**
   * Creates new form LogonApp
   */
  public Logon(String errmsg) {
    This = this;
    if (errmsg != null) {
      showError(errmsg);
    }
    try {
      load_config();
      initComponents();
      loadNetworkIcons();
      if (new File("/etc/.lastLogon").exists()) {
        Properties props = new Properties();
        props.load(new FileInputStream("/etc/.lastLogon"));
        lastUser = props.getProperty("lastUser");
        if (lastUser == null) lastUser = "";
        lastDomain = props.getProperty("lastDomain");
        if (lastDomain == null) lastDomain = "";
      } else {
        lastUser = "";
        lastDomain = "";
      }
      listUsers();
      if (lastUser.length() == 0) {
        username.setSelectedItem("");
        username.grabFocus();
      } else {
        username.setSelectedItem(lastUser);
        password.grabFocus();
      }
      JFImage icon = loadIcon("jflogon-power");
      icon = scaleIcon(icon, 18, 18);
      shutdown.setText("");
      shutdown.setIcon(icon);
      icon = loadIcon("jflogon-network");
      icon = scaleIcon(icon, 18, 18);
      network.setText("");
      network.setIcon(icon);
      pack();
      JFAWT.centerWindow(this);
      //connect to JBus
      if (jbusServer == null) {
        jbusServer = new JBusServer(SystemBusNames.logon, new JBusMethods());
        jbusServer.connect();
      }
      getWAPList();
    } catch (Throwable t) {
      JFLog.log(t);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    xMenu = new javax.swing.JPopupMenu();
    Sleep = new javax.swing.JMenuItem();
    Reboot = new javax.swing.JMenuItem();
    Shutdown = new javax.swing.JMenuItem();
    NetworkPopup = new javax.swing.JPopupMenu();
    lUser = new javax.swing.JLabel();
    username = new javax.swing.JComboBox<>();
    lPass = new javax.swing.JLabel();
    password = new javax.swing.JPasswordField();
    logon = new javax.swing.JButton();
    shutdown = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    network = new javax.swing.JButton();

    Sleep.setText("Sleep");
    Sleep.setToolTipText("");
    Sleep.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        SleepActionPerformed(evt);
      }
    });
    xMenu.add(Sleep);

    Reboot.setText("Reboot");
    Reboot.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        RebootActionPerformed(evt);
      }
    });
    xMenu.add(Reboot);

    Shutdown.setText("Shutdown");
    Shutdown.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ShutdownActionPerformed(evt);
      }
    });
    xMenu.add(Shutdown);

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    lUser.setText("Username");

    username.setEditable(true);
    username.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        usernameKeyReleased(evt);
      }
      public void keyTyped(java.awt.event.KeyEvent evt) {
        usernameKeyTyped(evt);
      }
    });

    lPass.setText("Password");

    password.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        passwordKeyReleased(evt);
      }
      public void keyTyped(java.awt.event.KeyEvent evt) {
        passwordKeyTyped(evt);
      }
    });

    logon.setText("Logon");
    logon.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        logonActionPerformed(evt);
      }
    });

    shutdown.setText("X");
    shutdown.setComponentPopupMenu(xMenu);
    shutdown.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        shutdownActionPerformed(evt);
      }
    });

    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel4.setText("Logon");

    network.setText("W");
    network.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        networkActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lUser)
              .addComponent(lPass))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(password)
              .addComponent(username, 0, 276, Short.MAX_VALUE)))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(shutdown)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(network)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logon)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel4)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lUser)
          .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lPass)
          .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(logon)
          .addComponent(shutdown)
          .addComponent(network))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void logonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logonActionPerformed
    doLogon();
  }//GEN-LAST:event_logonActionPerformed

  private void shutdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shutdownActionPerformed
    xMenu.show(shutdown, 0, shutdown.getHeight());
  }//GEN-LAST:event_shutdownActionPerformed

  private void RebootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RebootActionPerformed
    setVisible(false);
    if (!JFAWT.showConfirm("Confirm", "Are you sure you want to reboot?")) {
      setVisible(true);
      return;
    }
    reboot();
  }//GEN-LAST:event_RebootActionPerformed

  private void ShutdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShutdownActionPerformed
    setVisible(false);
    if (!JFAWT.showConfirm("Confirm", "Are you sure you want to shutdown?")) {
      setVisible(true);
      return;
    }
    shutdown("-P");
  }//GEN-LAST:event_ShutdownActionPerformed

  private void SleepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SleepActionPerformed
    try {
      JF.exec(new String[] {"pm-suspend"});
    } catch (Exception e) {
      JFLog.log(e);
    }
  }//GEN-LAST:event_SleepActionPerformed

  private void networkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkActionPerformed
    if (networkTimer != null) {
      cancelNetworkConnection();
    } else {
      getVPNList();  //triggers showNetworkPopup();
    }
  }//GEN-LAST:event_networkActionPerformed

  private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
    int kc = evt.getKeyCode();
    int mod = evt.getModifiersEx() & JFAWT.KEY_MASKS;
    if ((kc == KeyEvent.VK_ENTER) && (mod == 0)) {
      logonActionPerformed(null);
    }
  }//GEN-LAST:event_usernameKeyTyped

  private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
    int kc = evt.getKeyCode();
    int mod = evt.getModifiersEx() & JFAWT.KEY_MASKS;
    if ((kc == KeyEvent.VK_ENTER) && (mod == 0)) {
      logonActionPerformed(null);
    }
  }//GEN-LAST:event_passwordKeyTyped

  private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased
    int kc = evt.getKeyCode();
    int mod = evt.getModifiersEx() & JFAWT.KEY_MASKS;
    if ((kc == KeyEvent.VK_ENTER) && (mod == 0)) {
      logonActionPerformed(null);
    }
  }//GEN-LAST:event_passwordKeyReleased

  private void usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyReleased
    int kc = evt.getKeyCode();
    int mod = evt.getModifiersEx() & JFAWT.KEY_MASKS;
    if ((kc == KeyEvent.VK_ENTER) && (mod == 0)) {
      logonActionPerformed(null);
    }
  }//GEN-LAST:event_usernameKeyReleased

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPopupMenu NetworkPopup;
  private javax.swing.JMenuItem Reboot;
  private javax.swing.JMenuItem Shutdown;
  private javax.swing.JMenuItem Sleep;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel lPass;
  private javax.swing.JLabel lUser;
  private javax.swing.JButton logon;
  private javax.swing.JButton network;
  private javax.swing.JPasswordField password;
  private javax.swing.JButton shutdown;
  private javax.swing.JComboBox<String> username;
  private javax.swing.JPopupMenu xMenu;
  // End of variables declaration//GEN-END:variables

  public static JBusServer jbusServer;
  public static Logon This;
  private String lastUser, lastDomain;

  private void listUsers() {
    username.removeAllItems();
    try {
      FileInputStream fis = new FileInputStream("/etc/passwd");
      int len = fis.available();
      byte buf[] = new byte[len];
      int pos = 0;
      while (pos < len) {
        int read = fis.read(buf, pos, len-pos);
        if (read <= 0) throw new Exception("file error");
        pos += read;
      }
      fis.close();
      String passwd = new String(buf);
      String lns[] = passwd.split("\n");
      for(int a=0;a<lns.length;a++) {
        String f[] = lns[a].split(":", -1);
        //0=user : 1=x : 2=uid : 3=gid : 4=comment : 5=home : 6=shell
        if (f[0].equals("root")) continue;
        if (!f[6].equals("/bin/bash")) continue;
        username.addItem(f[0]);
      }
    } catch (Exception e) {
      JFLog.log(e);
    }
  }

  private ArrayList<String> server = new ArrayList<String>();
  private String errmsg;
  private String envs[];
  private String user, pass;
  private boolean domainLogon;
  private long pam;

  private void doLogon() {
    user = (String)username.getSelectedItem();
    pass = new String(password.getPassword());
    if (!authUser()) {
      showError("Logon Failed : " + errmsg);
      return;
    }
    //save lastUser/lastDomain
    try {
      Properties props = new Properties();
      props.setProperty("lastUser", (String)username.getSelectedItem());
      props.store(new FileOutputStream("/etc/.lastLogon"), "");
    } catch (Exception e) {
      JFLog.log(e);
    }
    runSession();
  }

  private boolean authUser() {
    errmsg = "Auth failed";
    envs = null;
    domainLogon = false;
    pam = LinuxAPI.getInstance().pamOpen(user, pass, LinuxAPI.pamGetBackend());
    return pam != 0;
  }

  private void runSession() {
    dispose();
    if (is_wayland) {
      boolean res = (Boolean)jbusServer.invoke(SystemBusNames.system, "stopDisplayManager");
      if (!res) {
        new Logon("Failed to stop display manager").setVisible(true);
        return;
      }
    }
    new Thread() {
      public void run() {
        try {
          runSession(user, "/usr/bin/jfdesktop", envs, domainLogon);
        } catch (Exception e) {
          JFAWT.showError("Session Failed", e.toString());
        }
        if (is_wayland) {
          boolean res = (Boolean)jbusServer.invoke(SystemBusNames.system, "startDisplayManager");
          if (!res) {
            JFLog.log("startDisplayManager failed!");
          }
        } else {
          Linux.x11_rr_reset("800x600");
        }
        java.awt.EventQueue.invokeLater(new Runnable() {public void run() {
          new Logon(null).setVisible(true);
        }});
      }
    }.start();
  }

  public static byte mcookie[] = new byte[16];

  private static void write_xauth(String fn) throws Exception {
    FileOutputStream fos = new FileOutputStream(fn);
    fos.write(new byte[] { (byte)0xfc, 0x00 });  //uint16 = 252
    fos.write(new byte[] { 0x00, 0x00 });  //uint16 = 0 (string length)
    fos.write(new byte[] { 0x00, 0x00 });  //uint16 = 0 (string length)
    fos.write(new byte[] { 0x12, 0x00 });  //uint16 = 0x12 (string length)
    fos.write("MIT-MAGIC-COOKIE-1".getBytes());  //magic string
    fos.write(new byte[] { 0x10, 0x00 });  //uint16 = 0x10 (data length)
    fos.write(mcookie);  //cookie
    fos.close();
  }

  private static void chown_xauth(String fn, String user) throws Exception {
    try {
      JF.exec(new String[] {"chown", user+":"+user, fn});
    } catch (Exception e) {
      JFLog.log(e);
    }
  }

  public void runSession(String user, String session, String[] envs, boolean domainLogon) {
    //NOTE : this is running in jflogon-ui process
    LinuxAPI api = LinuxAPI.getInstance();
    try {
      getUserDetails(user);
      if (!is_wayland) {
        String xauthFile = homePath + "/.Xauthority";
        write_xauth(xauthFile);
        chown_xauth(xauthFile, user);
      }
      if (!Linux.isMemberOf(user, "audio")) {
        //pulseaudio requires user to be member of 'audio' group
        JF.exec(new String[] {"usermod", "-aG", "audio", user});
      }
      if (!Linux.isMemberOf(user, "sambashare")) {
        //net usershare requires user to be member of 'sambashare' group
        JF.exec(new String[] {"usermod", "-aG", "sambashare", user});
      }
      if (!Linux.isMemberOf(user, "video")) {
        //video4linux requires user to be a member of 'video' group
        JF.exec(new String[] {"usermod", "-aG", "video", user});
      }
      String jid = "j" + Math.abs(new Random().nextInt());
      if (pam != 0) {
        api.pamSetItem(pam, LinuxAPI.PAM_TTY, "/dev/tty0");
        api.pamOpenSession(pam);
      }
      String cmd[] = new String[] {
        "/usr/sbin/runuser",
        "-u",
        user,
        session
      };
      ProcessBuilder pb = new ProcessBuilder(cmd);
      Map<String,String> env = pb.environment();
      env.put("USER", user);
      env.put("LOGNAME", user);
      env.put("SHELL", shellPath);
      env.put("HOME", homePath);
      env.put("JID", jid);
      String xdg_runtime_dir = "/run/user/" + uid;
      new File(xdg_runtime_dir).mkdir();
      Linux.chown(xdg_runtime_dir, user);
      env.put("XDG_RUNTIME_DIR", xdg_runtime_dir);
      if (is_wayland) {
        env.remove("WAYLAND_DISPLAY");  //inherited from parent
      } else {
        env.put("XAUTHORITY", homePath + "/.Xauthority");
        env.put("DISPLAY", ":0");
      }
      if (envs != null) {
        for(String e : envs) {
          int idx = e.indexOf('=');
          if (idx == -1) continue;
          String name = e.substring(0, idx);
          String value = e.substring(idx + 1);
          env.put(name, value);
        }
      }
      JFLog.log("JID=" + jid);
      JFLog.log("Starting session:" + session + ";user=" + user + ";uid=" + uid);
      try {
        Process p = pb.start();
        p.waitFor();
      } catch (Throwable t2) {
        JFLog.log(t2);
      }
      if (pam != 0) {
        api.pamCloseSession(pam);
        api.pamClose(pam);
        pam = 0;
      }
      JFLog.log("Session has terminated");
      JFLog.log("Killing all processes for user " + user);
      JF.exec(new String[] {"killall", "-u", user});  //ensure session ended
      JF.sleep(1500);  //wait for windows to close
    } catch (Throwable t1) {
      JFLog.log(t1);
    }
  }

  public static String uid, gid, homePath, shellPath;

  public static void getUserDetails(String user) throws Exception {
    //find path from /etc/passwd
    //passwd = user_name:x:uid:gid:full_name:home_dir:shell
    FileInputStream fis = new FileInputStream("/etc/passwd");
    int len = fis.available();
    byte passwd[] = new byte[len];
    fis.read(passwd);
    String text = new String(passwd);
    String lns[] = text.split("\n");
    for(int ln=0;ln<lns.length;ln++) {
      String fs[] = lns[ln].split(":");
      if (!fs[0].equals(user)) continue;
      uid = fs[2];
      gid = fs[3];
      homePath = fs[5];
      shellPath = fs[6];
      fis.close();
      return;
    }
    fis.close();
    throw new Exception("user not found");
  }

  private void showError(String msg) {
    setVisible(false);
    setEnabled(false);
    JFAWT.showError("Error", msg);
    setVisible(true);
    setEnabled(true);
  }

  public static JFImage loadIcon(String iconName) {
    JFImage icon = new JFImage();
    icon.loadPNG(icon.getClass().getClassLoader().getResourceAsStream(iconName + ".png"));
    return icon;
  }

  public static JFImage scaleIcon(JFImage image,int x,int y) {
    if ((image.getWidth() == x) && (image.getHeight() == y)) return image;
    JFImage scale = new JFImage(x, y);
    scale.fill(0, 0, x, y, 0, true);
    scale.getGraphics().drawImage(image.getImage(), 0,0, x-1,y-1, 0,0, image.getWidth()-1,image.getHeight()-1, null);
    return scale;
  }

  public void actionPerformed(ActionEvent ae) {
    String action = ae.getActionCommand();
    if (action.startsWith("#vpn#")) {
      connectVPN(action.substring(5));
    } else if (action.startsWith("#wap#")) {
      int idx = Integer.valueOf(action.substring(5));
      AccessPoint wap = wapItems.get(idx);
      connectWAP(wap.dev, wap.ssid, wap.encType);
    }
  }

  private String[] wapList;
  private String vpnList;
  private String[] vpnList2;

  private boolean checkWireless() {
    ShellProcess sp = new ShellProcess();
    String output = sp.run(new String[] {"iwconfig"}, false);
    if (output.indexOf("ESSID") == -1) return false;
    return true;
  }

  private static String quote(String str) {
    return "\"" + str + "\"";
  }

  private void getWAPList() {
    JFDictionary wapList = (JFDictionary)jbusServer.invoke(SystemBusNames.network, "getWAPList");
  }

  private void getVPNList() {
    String list = (String)jbusServer.invoke(SystemBusNames.network, "getVPNList");
  }

  ArrayList<AccessPoint> wapItems = new ArrayList<AccessPoint>();

  private void showNetworkPopup() {
    NetworkPopup.removeAll();
    if (checkWireless()) {
      JMenu subWireless = new JMenu("Wireless");
      NetworkPopup.add(subWireless);
      //list wireless access points
      boolean wapActive = false;
      String dev = null;
      int cnt = 0;
      int w = 0;
      wapItems.clear();
      for (String wap : wapList) {
        AccessPoint ap = new AccessPoint();
        String ssid = wap;
//        String encType = ???
//        ap.dev = dev;
        ap.ssid = ssid;
//        ap.encType = encType;
        wapItems.add(ap);
        JMenuItem w1 = new JMenuItem(ssid);
        w1.setActionCommand("#wap#" + (w++));
        w1.addActionListener(this);
        subWireless.add(w1);
        cnt--;
      }

      if (wapActive) {
        JMenuItem w1 = new JMenuItem("Disconnect...");
        w1.setActionCommand("#wap-disconnect");
        w1.addActionListener(this);
        subWireless.add(w1);
      }
    }

    //list vpn
    JMenu subVPN = new JMenu("VPN");
    NetworkPopup.add(subVPN);
    //list VPN
    vpnList2 = vpnList.split("[|]");
    for(int a=0;a<vpnList2.length;a++) {
      JMenuItem v1 = new JMenuItem(vpnList2[a]);
      v1.setActionCommand("#vpn#" + a);
      v1.addActionListener(this);
      subVPN.add(v1);
    }

    NetworkPopup.show(network, 0, network.getHeight());
  }

  private java.util.Timer networkTimer;
  private int networkIconIdx;
  private JFImage networkIcons[];
  private Icon networkOrgIcon;
  private final Object networkLock = new Object();
  private int networkTimerCount;
  private String cancelNetworkMethod;

  private void loadNetworkIcons() {
    networkIcons = new JFImage[3];
    for(int a=0;a<3;a++) {
      JFImage img = loadIcon("jflogon-network-" + (a+1));
      networkIcons[a] = scaleIcon(img, 18, 18);
    }
  }

  private void startNetworkTimer(String method) {
    if (networkTimer != null) return;
    cancelNetworkMethod = method;
    networkIconIdx = 0;
    networkTimerCount = 0;
    networkTimer = new java.util.Timer();
    networkTimer.schedule(new TimerTask() {
      public void run() {
        synchronized(networkLock) {
          if (networkTimer == null) return;
          networkTimerCount++;
          if (networkTimerCount == 60) {
            //after 30 seconds
            networkTimer.cancel();
            networkTimer = null;
            resetNetworkIcon();
            cancelNetworkConnection();
            return;
          }
          try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
              public void run() {
                if (networkOrgIcon == null) networkOrgIcon = network.getIcon();
                networkIconIdx++;
                if (networkIconIdx == networkIcons.length) networkIconIdx = 0;
                network.setIcon(networkIcons[networkIconIdx]);
              }
            });
          } catch (Exception e) {
            JFLog.log(e);
          }
        }
      }
    }, 0, 500);
  }

  private void stopNetworkTimer() {
    synchronized(networkLock) {
      networkTimer.cancel();
      networkTimer = null;
    }
    resetNetworkIcon();
  }

  private void resetNetworkIcon() {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        network.setIcon(networkOrgIcon);
        networkOrgIcon = null;
      }
    });
  }

  private void cancelNetworkConnection() {
    if (cancelNetworkMethod == null) return;
    jbusServer.invoke(SystemBusNames.network, cancelNetworkMethod);
    cancelNetworkMethod = null;
    showNetworkFailed();
  }

  private void showNetworkFailed() {
    JFAWT.showError("Error", "Connection failed!");
  }

  private void disconnectVPN(String name) {
    jbusServer.invoke(SystemBusNames.network, "disconnectVPN", name);
  }

  private void connectVPN(String name) {
    if (name.endsWith(" *")) {
      disconnectVPN(name.substring(0, name.length() - 2));
    } else {
      startNetworkTimer("cancelVPN");
      jbusServer.invoke(SystemBusNames.network, "connectVPN", name);
    }
  }

  private void disconnectWAP(String ssid) {
    jbusServer.invoke(SystemBusNames.network, "disconnectWAP" , ssid);
  }

  private void connectWAP(String dev, String ssid, String encType) {
    if (ssid.endsWith(" *")) {
      disconnectWAP(ssid.substring(0, ssid.length() - 2));
    } else {
      String key = "";
      if (encType.equals("WEP")) {
        key = JFAWT.getString("Enter WEP encryption key (26 or 10 hex digits)", "");
      } else if (encType.equals("WPA")) {
        key = JFAWT.getString("Enter WPA pass phrase", "");
      }
      startNetworkTimer("cancelWAP");
      jbusServer.invoke(SystemBusNames.network, "connectWAP", dev, ssid, encType, key);
    }
  }

  public class JBusMethods {
    public boolean setVPNList(String list) {
      vpnList = list;
      showNetworkPopup();
      return true;
    }
    public boolean vpnFailed(String id) {
      stopNetworkTimer();
      showNetworkFailed();
      return true;
    }
    public boolean vpnSuccess(String id) {
      stopNetworkTimer();
      return true;
    }
    public boolean wapFailed() {
      stopNetworkTimer();
      showNetworkFailed();
      return true;
    }
    public boolean wapSuccess() {
      stopNetworkTimer();
      return true;
    }
  }

  private static String getProperty(String name) {
    String prop = props.getProperty(name);
    if (prop == null) prop = "";
    return prop.trim();
  }

  private static void log_env() {
    JFLog.log(LOG_DEFAULT, "Environment:");
    String[] envs = JF.getEnvironment();
    for(String e : envs) {
      JFLog.log(LOG_DEFAULT, e);
    }
  }

  /** Reboots PC */
  public static void reboot() {
    try {
//      stop();
//      showPlymouth();
      JFLog.log("Rebooting...");
      JF.exec(new String[] {"reboot"});
    } catch (Exception e) {
      JFLog.log(e);
    }
  }

  /** Shuts down PC
   * @param type "-P" = powerdown, "-H"=halt
   */
  public static void shutdown(String type) {
    try {
//      stop();
//      showPlymouth();
      JFLog.log("Shutting down...,type=" + type);
      JF.exec(new String[] {"shutdown " + type + " now"});
    } catch (Exception e) {
      JFLog.log(e);
    }
  }

  public static void main(String[] args) {
    JFLog.init(LOG_DEFAULT, "/var/log/jflogon-ui.log", true);
    log_env();
    //display greeter
    try {
      Logon logon = new Logon(null);
      logon.setVisible(true);
    } catch (Throwable t) {
      JFLog.log(t);
    }
  }
}
