package javaforce.ffm;

import java.io.*;
import java.util.*;
import java.lang.reflect.*;
import java.lang.annotation.*;

import javaforce.*;

/** Generates FFM code from API class.
 *
 * @author pquiring
 */

public class GenFFM {
  public static void main(String[] args) {
    int idx;
    if (args.length != 5) {
      System.out.println("Usage: GenFFM class_in fileout.java package(s) implements_extends baseclass");
      return;
    }

    String fin = args[0];
    String fout = args[1].replaceAll("\\\\", "/");
    String pack = args[2];
    String i_e = args[3];
    String basecls = args[4];

    String[] libs = null;

    System.out.println("Converting " + fin + " to " + fout);

    String cls_in = fin;

    String cls_out = fout;
    idx = fout.lastIndexOf('/');
    if (idx != -1) {
      cls_out = fout.substring(idx + 1);
    }
    idx = cls_out.indexOf('.');
    cls_out = cls_out.substring(0, idx);


    Method[] methods = null;
    String method_name = null;

    StringBuilder src = new StringBuilder();
    StringBuilder ctor = new StringBuilder();

    ArrayList<String> funcs = new ArrayList<>();

    try {
      ArrayList<String> list = new ArrayList<>();
      Class<?> cls = Class.forName(cls_in);
      Annotation[] annos = cls.getAnnotations();
      for(Annotation anno : annos) {
        String annostr = anno.toString();
        if (annostr.startsWith("@javaforce.ffm.NativeLibrary")) {
          int i1 = annostr.indexOf("\"");
          int i2 = annostr.lastIndexOf("\"");
          libs = annostr.substring(i1 + 1, i2).split(",");
        }
      }
      methods = cls.getDeclaredMethods();

      //sort methods
      Arrays.sort(methods, (m1, m2) -> {
        return m1.toGenericString().compareTo(m2.toGenericString());
      });

      src.append("package javaforce.ffm;\n");
      src.append("\n");
      if (basecls.equals("X11API")) {
        src.append("import java.awt.*;\n");
      }
      src.append("import java.lang.foreign.*;\n");
      src.append("import java.lang.invoke.*;\n");
      src.append("import static java.lang.foreign.ValueLayout.*;\n");
      src.append("\n");
      src.append("import javaforce.*;\n");
      src.append("import javaforce.ffm.*;\n");
      String[] packs = pack.split(",");
      for(String p : packs) {
        src.append("import javaforce." + p + ".*;\n");
      }
      src.append("\n");
      src.append("/** " + basecls + " FFM implementation.\n");
      src.append(" *\n");
      src.append(" * Generated by GenFFM - DO NOT EDIT\n");
      src.append(" */\n");
      src.append("\n");
      src.append("\n");
      src.append("public class " + cls_out + " " + i_e + " " + basecls + " {\n");
      src.append("\n");
//      src.append("  private Arena arena;\n");
      src.append("  private FFM ffm;\n");
      src.append("\n");
      src.append("  private static " + cls_out + " instance;\n");
      src.append("  public static synchronized " + cls_out + " getInstance() {\n");
      src.append("    if (instance == null) {\n");
      src.append("      instance = new " + cls_out + "();\n");
      src.append("      if (!instance.ffm_init()) {\n");
      src.append("        JFLog.log(\"" + cls_out + " init failed!\");\n");
      src.append("        instance = null;\n");
      src.append("      }\n");
      src.append("    }\n");
      src.append("    return instance;\n");
      src.append("  }\n");
      src.append("\n");
      ctor.append("  private boolean ffm_init() {\n");
      ctor.append("    if (FFM.debug) JFLog.log(\"" + cls_out + " init started\");\n");
      ctor.append("    MethodHandle init;\n");
      ctor.append("    ffm = FFM.getInstance();\n");
      if (libs != null) {
        ctor.append("    Library[] libs = new Library[] {");
        for(int l=0;l<libs.length;l++) {
          if (l > 0) ctor.append(",");
          ctor.append("new Library(\"");
          ctor.append(libs[l]);
          ctor.append("\")");
        }
        ctor.append("};\n");
        ctor.append("    Library.findLibraries(null, libs);\n");
        ctor.append("    Arena arena = Arena.ofAuto();\n");
      }
      ctor.append("    init = ffm.getFunction(\"" + basecls + "init\", ffm.getFunctionDesciptor(ValueLayout.JAVA_BOOLEAN");
      if (libs != null) {
        for(int l=0;l<libs.length;l++) {
          ctor.append(",ADDRESS");
        }
      }
      ctor.append("));\n");
      ctor.append("    if (init == null) return false;\n");
      ctor.append("    try {if (!(boolean)init.invokeExact(");
      if (libs != null) {
        for(int l=0;l<libs.length;l++) {
          if (l > 0) {
            ctor.append(",");
          }
          ctor.append("libs[" + l + "].getPath(arena)");
        }
      }
      ctor.append(")) return false;} catch (Throwable t) {JFLog.log(t); return false;}\n");
      ctor.append("\n");
      for(Method jmethod : methods) {
        if ((jmethod.getModifiers() & Modifier.ABSTRACT) == 0) continue;
        Class<?> jret = jmethod.getReturnType();
        Class<?>[] jargs = jmethod.getParameterTypes();
        method_name = jmethod.getName();
        String java_ret_type = getType(jret.toGenericString());
        String ValueLayout_ret_type = null;
        if (java_ret_type.equals("java.lang.String")) {
          ValueLayout_ret_type = "ADDRESS";
        } else {
          ValueLayout_ret_type = "JAVA_" + java_ret_type.toUpperCase();
        }
        boolean isRetVoid = java_ret_type.equals("void");
        boolean isRetArray = java_ret_type.endsWith("[]");
        if (isRetArray) {
          java_ret_type = java_ret_type.substring(0, java_ret_type.length() - 2);
        }
        String func_name = method_name;
        boolean isDup = false;
        if (funcs.contains(func_name)) {
          isDup = true;
        } else {
          funcs.add(func_name);
        }
        if (!isDup) {
          src.append("  private MethodHandle " + func_name + ";\n");
        }
        src.append("  public " + java_ret_type);
        if (isRetArray) {
          src.append("[]");
        }
        src.append(" " + func_name + "(");  //add args

        StringBuilder ctor2 = new StringBuilder();

        StringBuilder method = new StringBuilder();
        StringBuilder arrays = new StringBuilder();
        method.append("{ try { ");
        boolean arena_needed = false;
        int before_invoke = method.length();
        if (!isRetVoid) {
          if (isRetArray) {
            method.append("FFM.createFFMArray();");
          } else {
            if (java_ret_type.equals("java.lang.String")) {
              method.append("String _ret_value_ = FFM.getString((MemorySegment)");
            } else {
              method.append(java_ret_type + " _ret_value_ = (" + java_ret_type + ")");
            }
          }
        }
        boolean first_method = true;
        boolean first_src = true;
        boolean first_ctor = true;
        String object = null;
        method.append(func_name);
        method.append(".invokeExact(");

        ctor2.append("    " + func_name + " = ffm.getFunctionPtr");
        ctor2.append("(\"_" + func_name + "\", ffm.getFunctionDesciptor");
        if (isRetVoid) {
          ctor2.append("Void(");
        } else {
          if (isRetArray) {
            ctor2.append("Void");
          }
          ctor2.append("(");
          if (isRetArray) {
            //nop
          } else {
            ctor2.append(ValueLayout_ret_type);
            first_ctor = false;
          }
        }
        ArrayList<String> array_names = new ArrayList<>();
        ArrayList<String> struct_names = new ArrayList<>();
        int aidx = 1;
        for(Class<?> arg : jargs) {
          String java_type = getType(arg.toGenericString());
          String ValueLayout_type = null;
          String arg_name = "a" + (aidx++);
          boolean isArray = false;
          String array_type = null;
          if (java_type.endsWith("[]")) {
            isArray = true;
            String base_type = java_type.substring(0, java_type.length() - 2);
            ValueLayout_type = "ADDRESS";
            array_type = "JAVA_" + base_type.toUpperCase();
          } else {
            if (isPrimitiveType(java_type)) {
              ValueLayout_type = "JAVA_" + java_type.toUpperCase();
            } else if (java_type.equals("javaforce.ui.Window")) {
              ValueLayout_type = "JAVA_LONG";
            } else if (FFMStruct.isStruct(arg)) {
              ValueLayout_type = "ADDRESS";
            } else if (FFMType.isType(arg)) {
              if (FFMType.isTypeInt(arg)) {
                ValueLayout_type = "JAVA_INT";
              } else if (FFMType.isTypeLong(arg)) {
                ValueLayout_type = "JAVA_LONG";
              }
            } else {
              ValueLayout_type = "ADDRESS";
            }
          }
          if (first_src) {
            first_src = false;
          } else {
            src.append(",");
          }
          if (first_method) {
            first_method = false;
          } else {
            method.append(",");
          }
          if (first_ctor) {
            first_ctor = false;
          } else {
            ctor2.append(",");
          }
          src.append(java_type + " " + arg_name);
          if (isArray) {
            array_names.add(arg_name);
            String segment_name = "_array_" + arg_name;
            arrays.append("MemorySegment " + segment_name + " = FFM.toMemory(");
            arrays.append("arena, ");
            arena_needed = true;
            arrays.append(arg_name + ");");
            method.append(segment_name);
          } else {
            if (java_type.equals("javaforce.media.MediaIO")) {
              method.append("FFM.upcall_MediaIO");
              method.insert(before_invoke, "FFM.setMediaIO(" + arg_name + ");");
            } else if (java_type.equals("javaforce.io.FolderListener")) {
              method.append("FFM.upcall_FolderListener_folderChangeEvent");
              method.insert(before_invoke, "FFM.setFolderListener(" + arg_name + ");");
            } else if (java_type.equals("javaforce.ui.UIEvents")) {
              method.append("FFM.upcall_UIEvents_dispatchEvent");
              method.insert(before_invoke, "FFM.setUIEvents(" + arg_name + ");");
            } else if (java_type.equals("java.lang.String")) {
              method.append("arena.allocateFrom(" + arg_name + ")");
              arena_needed = true;
            } else if (java_type.equals("javaforce.linux.X11Listener")) {
              method.append("FFM.upcall_X11Listener");
              method.insert(before_invoke, "FFM.setX11Listener(" + arg_name + ");");
            } else if (java_type.equals("javaforce.ui.Window")) {
              method.append("FFM.ref_object(" + arg_name + ")");
              object = arg_name;
            } else if (FFMType.isType(arg)) {
              method.append(arg_name + " == null ? 0 : " + arg_name + ".getValue()");
            } else if (FFMStruct.isStruct(arg)) {
              struct_names.add(arg_name);
              method.append("(MemorySegment)(" + arg_name + " == null ? MemorySegment.NULL : " + arg_name + ".marshall(arena))");
              arena_needed = true;
            } else {
              method.append(arg_name);
            }
          }
          ctor2.append(ValueLayout_type);
        }
        if (isRetArray) {
          method.append(");");
        } else {
          if (java_ret_type.equals("java.lang.String")) {
            method.append("));");
          } else {
            method.append(");");
          }
        }
        if (arrays.length() > 0) {
          //insert arrays after "{ try { "
          method.insert(8, arrays);
        }
        if (arena_needed) {
          //insert areana after "{ try { "
          method.insert(8, "Arena arena = Arena.ofAuto(); ");
        }
        for(String arg_name : array_names) {
          String segment_name = "_array_" + arg_name;
          method.append("FFM.copyBack(" + segment_name + "," + arg_name + ");");
        }
        for(String arg_name : struct_names) {
          method.append(arg_name + ".unmarshall();");
        }
        if (object != null) {
          method.append("FFM.unref_object(" + object + ");");
        }
        if (!isRetVoid) {
          method.append("return ");
          if (isRetArray) {
            method.append("(");
            method.append(java_ret_type);
            method.append("[])");
            method.append("FFM.getArray()");
          } else {
            method.append("_ret_value_");
          }
          method.append(";");
        }
        method.append(" } catch (Throwable t) { JFLog.log(t); ");
        if (!isRetVoid) {
          //must return a value
          method.append(" return ");
          if (isRetArray) {
            method.append("null");
          } else {
            switch (java_ret_type) {
              case "java.lang.String": method.append("null"); break;
              case "boolean": method.append("false"); break;
              case "char": method.append("(char)-1"); break;
              default: method.append("-1"); break;
            }
          }
          method.append(";");
        }
        method.append("} }\n");
        src.append(") ");
        src.append(method);  //{ invoke... }
        src.append("\n");
        ctor2.append(")");
        ctor2.append(");\n");
        if (!isDup) {
          ctor.append(ctor2);
        }
      }
      ctor.append("    if (FFM.debug) JFLog.log(\"" + cls_out + " init complete\");\n");
      ctor.append("    return true;\n");
      ctor.append("  }\n");
      src.append("\n");
      src.append(ctor);
      src.append("}\n");

    } catch (Exception e) {
      JFLog.log("Exception on Method:" + method_name);
      JFLog.log(e);
      return;
    }

    try {
      FileOutputStream fos = new FileOutputStream(fout);
      fos.write(src.toString().getBytes());
      fos.close();
    } catch (Exception e) {
      JFLog.log(e);
      return;
    }
  }
  private static String capitalize(String in) {
    char first_cap = Character.toUpperCase(in.charAt(0));
    return first_cap + in.substring(1);
  }
  private static boolean isPrimitiveType(String type) {
    switch (type) {
      case "boolean": return true;
      case "char": return true;
      case "byte": return true;
      case "short": return true;
      case "int": return true;
      case "long": return true;
      case "float": return true;
      case "double": return true;
      default: return false;
    }
  }
  private static String getType(String str) {
    int idx = str.lastIndexOf(' ');
    if (idx == -1) return str;
    return str.substring(idx + 1);
  }
}
