package javaforce.ffm;

import java.lang.foreign.*;
import java.lang.invoke.*;
import static java.lang.foreign.ValueLayout.*;

import javaforce.*;
import javaforce.ffm.*;
import javaforce.api.linux.*;
import javaforce.linux.*;

/** UnixSocketAPI FFM implementation.
 *
 * Generated by GenFFM - DO NOT EDIT
 */


public class UnixSocketFFM implements UnixSocketAPI {

  private FFM ffm;

  private static UnixSocketFFM instance;
  public static synchronized UnixSocketFFM getInstance() {
    if (instance == null) {
      instance = new UnixSocketFFM();
      if (!instance.ffm_init()) {
        JFLog.log("UnixSocketFFM init failed!");
        instance = null;
      }
    }
    return instance;
  }

  private MethodHandle usBind;
  public boolean usBind(int a1,java.lang.String a2) { try { Arena arena = Arena.ofAuto(); boolean _ret_value_ = (boolean)usBind.invokeExact(a1,(MemorySegment)(a2 == null ? MemorySegment.NULL : arena.allocateFrom(a2)));return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return false;} }

  private MethodHandle usClose;
  public boolean usClose(int a1) { try { boolean _ret_value_ = (boolean)usClose.invokeExact(a1);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return false;} }

  private MethodHandle usConnect;
  public boolean usConnect(int a1,java.lang.String a2) { try { Arena arena = Arena.ofAuto(); boolean _ret_value_ = (boolean)usConnect.invokeExact(a1,(MemorySegment)(a2 == null ? MemorySegment.NULL : arena.allocateFrom(a2)));return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return false;} }

  private MethodHandle usListen;
  public boolean usListen(int a1) { try { boolean _ret_value_ = (boolean)usListen.invokeExact(a1);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return false;} }

  private MethodHandle usRead;
  public boolean usRead(int a1,byte[] a2,int a3,int[] a4,int[] a5,int a6,int[] a7) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a2 = FFM.toMemory(arena, a2);MemorySegment _array_a4 = FFM.toMemory(arena, a4);MemorySegment _array_a5 = FFM.toMemory(arena, a5);MemorySegment _array_a7 = FFM.toMemory(arena, a7);boolean _ret_value_ = (boolean)usRead.invokeExact(a1,_array_a2,a3,_array_a4,_array_a5,a6,_array_a7);FFM.copyBack(_array_a2,a2);FFM.copyBack(_array_a4,a4);FFM.copyBack(_array_a5,a5);FFM.copyBack(_array_a7,a7);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return false;} }

  private MethodHandle usShutdown;
  public boolean usShutdown(int a1) { try { boolean _ret_value_ = (boolean)usShutdown.invokeExact(a1);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return false;} }

  private MethodHandle usWrite;
  public boolean usWrite(int a1,byte[] a2,int a3,int[] a4,int[] a5,int a6,int[] a7) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a2 = FFM.toMemory(arena, a2);MemorySegment _array_a4 = FFM.toMemory(arena, a4);MemorySegment _array_a5 = FFM.toMemory(arena, a5);MemorySegment _array_a7 = FFM.toMemory(arena, a7);boolean _ret_value_ = (boolean)usWrite.invokeExact(a1,_array_a2,a3,_array_a4,_array_a5,a6,_array_a7);FFM.copyBack(_array_a2,a2);FFM.copyBack(_array_a4,a4);FFM.copyBack(_array_a5,a5);FFM.copyBack(_array_a7,a7);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return false;} }

  private MethodHandle usAccept;
  public int usAccept(int a1) { try { int _ret_value_ = (int)usAccept.invokeExact(a1);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle usOpen;
  public int usOpen() { try { int _ret_value_ = (int)usOpen.invokeExact();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }


  private boolean ffm_init() {
    if (FFM.debug) JFLog.log("UnixSocketFFM init started");
    MethodHandle init;
    ffm = FFM.getInstance();
    init = ffm.getFunction("UnixSocketAPIinit", ffm.getFunctionDesciptor(ValueLayout.JAVA_BOOLEAN));
    if (init == null) return false;
    try {if (!(boolean)init.invokeExact()) return false;} catch (Throwable t) {JFLog.log(t); return false;}

    usBind = ffm.getFunctionPtr("_usBind", ffm.getFunctionDesciptor(JAVA_BOOLEAN,JAVA_INT,ADDRESS));
    usClose = ffm.getFunctionPtr("_usClose", ffm.getFunctionDesciptor(JAVA_BOOLEAN,JAVA_INT));
    usConnect = ffm.getFunctionPtr("_usConnect", ffm.getFunctionDesciptor(JAVA_BOOLEAN,JAVA_INT,ADDRESS));
    usListen = ffm.getFunctionPtr("_usListen", ffm.getFunctionDesciptor(JAVA_BOOLEAN,JAVA_INT));
    usRead = ffm.getFunctionPtr("_usRead", ffm.getFunctionDesciptor(JAVA_BOOLEAN,JAVA_INT,ADDRESS,JAVA_INT,ADDRESS,ADDRESS,JAVA_INT,ADDRESS));
    usShutdown = ffm.getFunctionPtr("_usShutdown", ffm.getFunctionDesciptor(JAVA_BOOLEAN,JAVA_INT));
    usWrite = ffm.getFunctionPtr("_usWrite", ffm.getFunctionDesciptor(JAVA_BOOLEAN,JAVA_INT,ADDRESS,JAVA_INT,ADDRESS,ADDRESS,JAVA_INT,ADDRESS));
    usAccept = ffm.getFunctionPtr("_usAccept", ffm.getFunctionDesciptor(JAVA_INT,JAVA_INT));
    usOpen = ffm.getFunctionPtr("_usOpen", ffm.getFunctionDesciptor(JAVA_INT));
    if (FFM.debug) JFLog.log("UnixSocketFFM init complete");
    return true;
  }
}
