package javaforce.ffm;

import java.lang.foreign.*;
import java.lang.invoke.*;
import static java.lang.foreign.ValueLayout.*;

import javaforce.*;
import javaforce.ffm.*;
import javaforce.vk.*;

/** VK FFM implementation.
 *
 * Generated by GenFFM - DO NOT EDIT
 */


public class VKFFM implements VK {

  private FFM ffm;

  private static VKFFM instance;
  public static synchronized VKFFM getInstance() {
    if (instance == null) {
      instance = new VKFFM();
      if (!instance.ffm_init()) {
        JFLog.log("VKFFM init failed!");
        instance = null;
      }
    }
    return instance;
  }

  private MethodHandle vkAcquireNextImageKHR;
  public int vkAcquireNextImageKHR(javaforce.vk.VkDevice a1,javaforce.vk.VkSwapchainKHR a2,long a3,javaforce.vk.VkSemaphore a4,javaforce.vk.VkFence a5,int[] a6) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a6 = FFM.toMemory(arena, a6);int _ret_value_ = (int)vkAcquireNextImageKHR.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),a3,a4 == null ? 0 : a4.getValue(),a5 == null ? 0 : a5.getValue(),_array_a6);FFM.copyBack(_array_a6,a6);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkAllocateCommandBuffers;
  public int vkAllocateCommandBuffers(javaforce.vk.VkDevice a1,javaforce.vk.VkCommandBufferAllocateInfo a2,javaforce.vk.VkCommandBuffer[] a3) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a3 = FFM.toMemory(arena, a3);int _ret_value_ = (int)vkAllocateCommandBuffers.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)),_array_a3);FFM.copyBack(_array_a3,a3);if (a2!=null) a2.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkAllocateMemory;
  public int vkAllocateMemory(javaforce.vk.VkDevice a1,javaforce.vk.VkMemoryAllocateInfo a2,javaforce.vk.VkAllocationCallbacks a3,javaforce.vk.VkDeviceMemory[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkAllocateMemory.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)),a3 == null ? 0 : a3.getValue(),_array_a4);FFM.copyBack(_array_a4,a4);if (a2!=null) a2.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkBeginCommandBuffer;
  public int vkBeginCommandBuffer(javaforce.vk.VkCommandBuffer a1,javaforce.vk.VkCommandBufferBeginInfo a2) { try { Arena arena = Arena.ofAuto(); int _ret_value_ = (int)vkBeginCommandBuffer.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)));if (a2!=null) a2.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkBindBufferMemory;
  public int vkBindBufferMemory(javaforce.vk.VkDevice a1,javaforce.vk.VkBuffer a2,javaforce.vk.VkDevice a3,javaforce.vk.VkDevice a4) { try { int _ret_value_ = (int)vkBindBufferMemory.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),a3 == null ? 0 : a3.getValue(),a4 == null ? 0 : a4.getValue());return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkBindImageMemory;
  public int vkBindImageMemory(javaforce.vk.VkDevice a1,javaforce.vk.VkImage a2,long a3,long a4) { try { int _ret_value_ = (int)vkBindImageMemory.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),a3,a4);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCmdBeginRenderPass;
  public int vkCmdBeginRenderPass(javaforce.vk.VkCommandBuffer a1,javaforce.vk.VkRenderPassBeginInfo a2,int a3) { try { Arena arena = Arena.ofAuto(); int _ret_value_ = (int)vkCmdBeginRenderPass.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)),a3);if (a2!=null) a2.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCmdBindDescriptorSets;
  public int vkCmdBindDescriptorSets(javaforce.vk.VkCommandBuffer a1,javaforce.vk.VkPipelineBindPoint a2,javaforce.vk.VkPipelineLayout a3,int a4,int a5,javaforce.vk.VkDescriptorSet[] a6,int a7,int[] a8) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a6 = FFM.toMemory(arena, a6);MemorySegment _array_a8 = FFM.toMemory(arena, a8);int _ret_value_ = (int)vkCmdBindDescriptorSets.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),a3 == null ? 0 : a3.getValue(),a4,a5,_array_a6,a7,_array_a8);FFM.copyBack(_array_a6,a6);FFM.copyBack(_array_a8,a8);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCmdBindPipeline;
  public int vkCmdBindPipeline(javaforce.vk.VkCommandBuffer a1,int a2,javaforce.vk.VkPipeline a3) { try { int _ret_value_ = (int)vkCmdBindPipeline.invokeExact(a1 == null ? 0 : a1.getValue(),a2,a3 == null ? 0 : a3.getValue());return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCmdBindVertexBuffers;
  public int vkCmdBindVertexBuffers(javaforce.vk.VkCommandBuffer a1,int a2,int a3,javaforce.vk.VkBuffer[] a4,javaforce.vk.VkDeviceSize[] a5) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);MemorySegment _array_a5 = FFM.toMemory(arena, a5);int _ret_value_ = (int)vkCmdBindVertexBuffers.invokeExact(a1 == null ? 0 : a1.getValue(),a2,a3,_array_a4,_array_a5);FFM.copyBack(_array_a4,a4);FFM.copyBack(_array_a5,a5);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCmdDraw;
  public int vkCmdDraw(javaforce.vk.VkCommandBuffer a1,int a2,int a3,int a4,int a5) { try { int _ret_value_ = (int)vkCmdDraw.invokeExact(a1 == null ? 0 : a1.getValue(),a2,a3,a4,a5);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCmdEndRenderPass;
  public int vkCmdEndRenderPass(javaforce.vk.VkCommandBuffer a1) { try { int _ret_value_ = (int)vkCmdEndRenderPass.invokeExact(a1 == null ? 0 : a1.getValue());return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCmdSetScissor;
  public int vkCmdSetScissor(javaforce.vk.VkCommandBuffer a1,int a2,int a3,javaforce.vk.VkRect2D[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkCmdSetScissor.invokeExact(a1 == null ? 0 : a1.getValue(),a2,a3,_array_a4);FFM.copyBack(_array_a4,a4);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCmdSetViewport;
  public int vkCmdSetViewport(javaforce.vk.VkCommandBuffer a1,int a2,int a3,javaforce.vk.VkViewport[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkCmdSetViewport.invokeExact(a1 == null ? 0 : a1.getValue(),a2,a3,_array_a4);FFM.copyBack(_array_a4,a4);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCreateBuffer;
  public int vkCreateBuffer(javaforce.vk.VkDevice a1,javaforce.vk.VkBufferCreateInfo a2,javaforce.vk.VkAllocationCallbacks a3,javaforce.vk.VkBuffer[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkCreateBuffer.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)),a3 == null ? 0 : a3.getValue(),_array_a4);FFM.copyBack(_array_a4,a4);if (a2!=null) a2.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCreateCommandPool;
  public int vkCreateCommandPool(javaforce.vk.VkDevice a1,javaforce.vk.VkCommandPoolCreateInfo a2,javaforce.vk.VkAllocationCallbacks a3,javaforce.vk.VkCommandPool[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkCreateCommandPool.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)),a3 == null ? 0 : a3.getValue(),_array_a4);FFM.copyBack(_array_a4,a4);if (a2!=null) a2.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCreateDescriptorPool;
  public int vkCreateDescriptorPool(javaforce.vk.VkDevice a1,javaforce.vk.VkDescriptorPoolCreateInfo a2,javaforce.vk.VkAllocationCallbacks a3,javaforce.vk.VkDescriptorPool[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkCreateDescriptorPool.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)),a3 == null ? 0 : a3.getValue(),_array_a4);FFM.copyBack(_array_a4,a4);if (a2!=null) a2.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCreateDescriptorSetLayout;
  public int vkCreateDescriptorSetLayout(javaforce.vk.VkDevice a1,javaforce.vk.VkDescriptorSetLayoutCreateInfo a2,javaforce.vk.VkAllocationCallbacks a3,javaforce.vk.VkDescriptorSetLayout[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkCreateDescriptorSetLayout.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)),a3 == null ? 0 : a3.getValue(),_array_a4);FFM.copyBack(_array_a4,a4);if (a2!=null) a2.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCreateDevice;
  public int vkCreateDevice(javaforce.vk.VkPhysicalDevice a1,javaforce.vk.VkDeviceCreateInfo a2,javaforce.vk.VkAllocationCallbacks a3,javaforce.vk.VkDevice[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkCreateDevice.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)),a3 == null ? 0 : a3.getValue(),_array_a4);FFM.copyBack(_array_a4,a4);if (a2!=null) a2.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCreateFence;
  public int vkCreateFence(javaforce.vk.VkDevice a1,javaforce.vk.VkFenceCreateInfo a2,javaforce.vk.VkAllocationCallbacks a3,javaforce.vk.VkFence[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkCreateFence.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)),a3 == null ? 0 : a3.getValue(),_array_a4);FFM.copyBack(_array_a4,a4);if (a2!=null) a2.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCreateFramebuffer;
  public int vkCreateFramebuffer(javaforce.vk.VkDevice a1,javaforce.vk.VkFramebufferCreateInfo a2,javaforce.vk.VkAllocationCallbacks a3,javaforce.vk.VkFramebuffer[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkCreateFramebuffer.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)),a3 == null ? 0 : a3.getValue(),_array_a4);FFM.copyBack(_array_a4,a4);if (a2!=null) a2.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCreateGraphicsPipelines;
  public int vkCreateGraphicsPipelines(javaforce.vk.VkDevice a1,javaforce.vk.VkPipelineCache a2,int a3,javaforce.vk.VkGraphicsPipelineCreateInfo[] a4,javaforce.vk.VkAllocationCallbacks a5,javaforce.vk.VkPipeline[] a6) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);MemorySegment _array_a6 = FFM.toMemory(arena, a6);int _ret_value_ = (int)vkCreateGraphicsPipelines.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),a3,_array_a4,a5 == null ? 0 : a5.getValue(),_array_a6);FFM.copyBack(_array_a4,a4);FFM.copyBack(_array_a6,a6);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCreateImage;
  public int vkCreateImage(javaforce.vk.VkDevice a1,javaforce.vk.VkImageCreateInfo a2,javaforce.vk.VkAllocationCallbacks a3,javaforce.vk.VkImage[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkCreateImage.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)),a3 == null ? 0 : a3.getValue(),_array_a4);FFM.copyBack(_array_a4,a4);if (a2!=null) a2.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCreateImageView;
  public int vkCreateImageView(javaforce.vk.VkDevice a1,javaforce.vk.VkImageViewCreateInfo a2,javaforce.vk.VkAllocationCallbacks a3,javaforce.vk.VkImageView[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkCreateImageView.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)),a3 == null ? 0 : a3.getValue(),_array_a4);FFM.copyBack(_array_a4,a4);if (a2!=null) a2.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCreateInstance;
  public int vkCreateInstance(javaforce.vk.VkInstanceCreateInfo a1,javaforce.vk.VkAllocationCallbacks a2,javaforce.vk.VkInstance[] a3) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a3 = FFM.toMemory(arena, a3);int _ret_value_ = (int)vkCreateInstance.invokeExact((MemorySegment)(a1 == null ? MemorySegment.NULL : a1.marshall(arena)),a2 == null ? 0 : a2.getValue(),_array_a3);FFM.copyBack(_array_a3,a3);if (a1!=null) a1.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCreatePipelineLayout;
  public int vkCreatePipelineLayout(javaforce.vk.VkDevice a1,javaforce.vk.VkPipelineLayoutCreateInfo a2,javaforce.vk.VkAllocationCallbacks a3,javaforce.vk.VkPipelineLayout[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkCreatePipelineLayout.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)),a3 == null ? 0 : a3.getValue(),_array_a4);FFM.copyBack(_array_a4,a4);if (a2!=null) a2.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCreateRenderPass;
  public int vkCreateRenderPass(javaforce.vk.VkDevice a1,javaforce.vk.VkRenderPassCreateInfo a2,javaforce.vk.VkAllocationCallbacks a3,javaforce.vk.VkRenderPass[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkCreateRenderPass.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)),a3 == null ? 0 : a3.getValue(),_array_a4);FFM.copyBack(_array_a4,a4);if (a2!=null) a2.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCreateRenderPass2;
  public int vkCreateRenderPass2(javaforce.vk.VkDevice a1,javaforce.vk.VkRenderPassCreateInfo2 a2,javaforce.vk.VkAllocationCallbacks a3,javaforce.vk.VkRenderPass[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkCreateRenderPass2.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)),a3 == null ? 0 : a3.getValue(),_array_a4);FFM.copyBack(_array_a4,a4);if (a2!=null) a2.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCreateSemaphore;
  public int vkCreateSemaphore(javaforce.vk.VkDevice a1,javaforce.vk.VkSemaphoreCreateInfo a2,javaforce.vk.VkAllocationCallbacks a3,javaforce.vk.VkSemaphore[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkCreateSemaphore.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)),a3 == null ? 0 : a3.getValue(),_array_a4);FFM.copyBack(_array_a4,a4);if (a2!=null) a2.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCreateShaderModule;
  public int vkCreateShaderModule(javaforce.vk.VkDevice a1,javaforce.vk.VkShaderModuleCreateInfo a2,javaforce.vk.VkAllocationCallbacks a3,javaforce.vk.VkShaderModule[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkCreateShaderModule.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)),a3 == null ? 0 : a3.getValue(),_array_a4);FFM.copyBack(_array_a4,a4);if (a2!=null) a2.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkCreateSwapchainKHR;
  public int vkCreateSwapchainKHR(javaforce.vk.VkDevice a1,javaforce.vk.VkSwapchainCreateInfoKHR a2,javaforce.vk.VkAllocationCallbacks a3,javaforce.vk.VkSwapchainKHR[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkCreateSwapchainKHR.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)),a3 == null ? 0 : a3.getValue(),_array_a4);FFM.copyBack(_array_a4,a4);if (a2!=null) a2.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkDestroyCommandPool;
  public int vkDestroyCommandPool(javaforce.vk.VkDevice a1,javaforce.vk.VkCommandPool a2,javaforce.vk.VkAllocationCallbacks a3) { try { int _ret_value_ = (int)vkDestroyCommandPool.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),a3 == null ? 0 : a3.getValue());return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkDestroyDevice;
  public int vkDestroyDevice(javaforce.vk.VkDevice a1,javaforce.vk.VkAllocationCallbacks a2) { try { int _ret_value_ = (int)vkDestroyDevice.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue());return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkDestroyFence;
  public int vkDestroyFence(javaforce.vk.VkDevice a1,javaforce.vk.VkFence a2,javaforce.vk.VkAllocationCallbacks a3) { try { int _ret_value_ = (int)vkDestroyFence.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),a3 == null ? 0 : a3.getValue());return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkDestroyFramebuffer;
  public int vkDestroyFramebuffer(javaforce.vk.VkDevice a1,javaforce.vk.VkFramebuffer a2,javaforce.vk.VkAllocationCallbacks a3) { try { int _ret_value_ = (int)vkDestroyFramebuffer.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),a3 == null ? 0 : a3.getValue());return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkDestroyImageView;
  public int vkDestroyImageView(javaforce.vk.VkDevice a1,javaforce.vk.VkImageView a2,javaforce.vk.VkAllocationCallbacks a3) { try { int _ret_value_ = (int)vkDestroyImageView.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),a3 == null ? 0 : a3.getValue());return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkDestroyInstance;
  public int vkDestroyInstance(javaforce.vk.VkInstance a1,javaforce.vk.VkAllocationCallbacks a2) { try { int _ret_value_ = (int)vkDestroyInstance.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue());return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkDestroyPipeline;
  public int vkDestroyPipeline(javaforce.vk.VkDevice a1,javaforce.vk.VkPipeline a2,javaforce.vk.VkAllocationCallbacks a3) { try { int _ret_value_ = (int)vkDestroyPipeline.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),a3 == null ? 0 : a3.getValue());return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkDestroyPipelineLayout;
  public int vkDestroyPipelineLayout(javaforce.vk.VkDevice a1,javaforce.vk.VkPipelineLayout a2,javaforce.vk.VkAllocationCallbacks a3) { try { int _ret_value_ = (int)vkDestroyPipelineLayout.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),a3 == null ? 0 : a3.getValue());return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkDestroyRenderPass;
  public int vkDestroyRenderPass(javaforce.vk.VkDevice a1,javaforce.vk.VkRenderPass a2,javaforce.vk.VkAllocationCallbacks a3) { try { int _ret_value_ = (int)vkDestroyRenderPass.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),a3 == null ? 0 : a3.getValue());return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkDestroySemaphore;
  public int vkDestroySemaphore(javaforce.vk.VkDevice a1,javaforce.vk.VkSemaphore a2,javaforce.vk.VkAllocationCallbacks a3) { try { int _ret_value_ = (int)vkDestroySemaphore.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),a3 == null ? 0 : a3.getValue());return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkDestroyShaderModule;
  public int vkDestroyShaderModule(javaforce.vk.VkDevice a1,javaforce.vk.VkShaderModule a2,javaforce.vk.VkAllocationCallbacks a3) { try { int _ret_value_ = (int)vkDestroyShaderModule.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),a3 == null ? 0 : a3.getValue());return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkDestroySurfaceKHR;
  public int vkDestroySurfaceKHR(javaforce.vk.VkInstance a1,javaforce.vk.VkSurfaceKHR a2,javaforce.vk.VkAllocationCallbacks a3) { try { int _ret_value_ = (int)vkDestroySurfaceKHR.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),a3 == null ? 0 : a3.getValue());return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkDestroySwapchainKHR;
  public int vkDestroySwapchainKHR(javaforce.vk.VkDevice a1,javaforce.vk.VkSwapchainKHR a2,javaforce.vk.VkAllocationCallbacks a3) { try { int _ret_value_ = (int)vkDestroySwapchainKHR.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),a3 == null ? 0 : a3.getValue());return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkDeviceWaitIdle;
  public int vkDeviceWaitIdle(javaforce.vk.VkDevice a1) { try { int _ret_value_ = (int)vkDeviceWaitIdle.invokeExact(a1 == null ? 0 : a1.getValue());return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkEndCommandBuffer;
  public int vkEndCommandBuffer(javaforce.vk.VkCommandBuffer a1) { try { int _ret_value_ = (int)vkEndCommandBuffer.invokeExact(a1 == null ? 0 : a1.getValue());return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkEnumerateDeviceExtensionProperties;
  public int vkEnumerateDeviceExtensionProperties(javaforce.vk.VkPhysicalDevice a1,java.lang.String a2,int[] a3,javaforce.vk.VkExtensionProperties[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a3 = FFM.toMemory(arena, a3);MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkEnumerateDeviceExtensionProperties.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : arena.allocateFrom(a2)),_array_a3,_array_a4);FFM.copyBack(_array_a3,a3);FFM.copyBack(_array_a4,a4);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkEnumeratePhysicalDevices;
  public int vkEnumeratePhysicalDevices(javaforce.vk.VkInstance a1,int[] a2,javaforce.vk.VkPhysicalDevice[] a3) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a2 = FFM.toMemory(arena, a2);MemorySegment _array_a3 = FFM.toMemory(arena, a3);int _ret_value_ = (int)vkEnumeratePhysicalDevices.invokeExact(a1 == null ? 0 : a1.getValue(),_array_a2,_array_a3);FFM.copyBack(_array_a2,a2);FFM.copyBack(_array_a3,a3);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkFreeCommandBuffers;
  public int vkFreeCommandBuffers(javaforce.vk.VkDevice a1,javaforce.vk.VkCommandPool a2,int a3,javaforce.vk.VkCommandBuffer[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkFreeCommandBuffers.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),a3,_array_a4);FFM.copyBack(_array_a4,a4);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkGetBufferMemoryRequirements;
  public int vkGetBufferMemoryRequirements(javaforce.vk.VkDevice a1,javaforce.vk.VkBuffer a2,javaforce.vk.VkMemoryRequirements a3) { try { Arena arena = Arena.ofAuto(); int _ret_value_ = (int)vkGetBufferMemoryRequirements.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),(MemorySegment)(a3 == null ? MemorySegment.NULL : a3.marshall(arena)));if (a3!=null) a3.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkGetDisplayModePropertiesKHR;
  public int vkGetDisplayModePropertiesKHR(javaforce.vk.VkPhysicalDevice a1,javaforce.vk.VkDisplayKHR a2,int[] a3,javaforce.vk.VkDisplayModePropertiesKHR a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a3 = FFM.toMemory(arena, a3);int _ret_value_ = (int)vkGetDisplayModePropertiesKHR.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),_array_a3,(MemorySegment)(a4 == null ? MemorySegment.NULL : a4.marshall(arena)));FFM.copyBack(_array_a3,a3);if (a4!=null) a4.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkGetDisplayPlaneCapabilitiesKHR;
  public int vkGetDisplayPlaneCapabilitiesKHR(javaforce.vk.VkPhysicalDevice a1,javaforce.vk.VkDisplayModeKHR a2,int a3,javaforce.vk.VkDisplayPlaneCapabilitiesKHR a4) { try { Arena arena = Arena.ofAuto(); int _ret_value_ = (int)vkGetDisplayPlaneCapabilitiesKHR.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),a3,(MemorySegment)(a4 == null ? MemorySegment.NULL : a4.marshall(arena)));if (a4!=null) a4.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkGetDisplayPlaneSupportedDisplaysKHR;
  public int vkGetDisplayPlaneSupportedDisplaysKHR(javaforce.vk.VkPhysicalDevice a1,int a2,int[] a3,javaforce.vk.VkDisplayKHR[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a3 = FFM.toMemory(arena, a3);MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkGetDisplayPlaneSupportedDisplaysKHR.invokeExact(a1 == null ? 0 : a1.getValue(),a2,_array_a3,_array_a4);FFM.copyBack(_array_a3,a3);FFM.copyBack(_array_a4,a4);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkGetImageMemoryRequirements;
  public int vkGetImageMemoryRequirements(javaforce.vk.VkDevice a1,javaforce.vk.VkImage a2,javaforce.vk.VkMemoryRequirements a3) { try { Arena arena = Arena.ofAuto(); int _ret_value_ = (int)vkGetImageMemoryRequirements.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),(MemorySegment)(a3 == null ? MemorySegment.NULL : a3.marshall(arena)));if (a3!=null) a3.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkGetPhysicalDeviceDisplayPlanePropertiesKHR;
  public int vkGetPhysicalDeviceDisplayPlanePropertiesKHR(javaforce.vk.VkPhysicalDevice a1,int[] a2,javaforce.vk.VkDisplayPlanePropertiesKHR a3) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a2 = FFM.toMemory(arena, a2);int _ret_value_ = (int)vkGetPhysicalDeviceDisplayPlanePropertiesKHR.invokeExact(a1 == null ? 0 : a1.getValue(),_array_a2,(MemorySegment)(a3 == null ? MemorySegment.NULL : a3.marshall(arena)));FFM.copyBack(_array_a2,a2);if (a3!=null) a3.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkGetPhysicalDeviceDisplayPropertiesKHR;
  public int vkGetPhysicalDeviceDisplayPropertiesKHR(javaforce.vk.VkPhysicalDevice a1,int[] a2,javaforce.vk.VkDisplayPropertiesKHR a3) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a2 = FFM.toMemory(arena, a2);int _ret_value_ = (int)vkGetPhysicalDeviceDisplayPropertiesKHR.invokeExact(a1 == null ? 0 : a1.getValue(),_array_a2,(MemorySegment)(a3 == null ? MemorySegment.NULL : a3.marshall(arena)));FFM.copyBack(_array_a2,a2);if (a3!=null) a3.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkGetPhysicalDeviceSurfaceCapabilitiesKHR;
  public int vkGetPhysicalDeviceSurfaceCapabilitiesKHR(javaforce.vk.VkPhysicalDevice a1,javaforce.vk.VkSurfaceKHR a2,javaforce.vk.VkSurfaceCapabilitiesKHR a3) { try { Arena arena = Arena.ofAuto(); int _ret_value_ = (int)vkGetPhysicalDeviceSurfaceCapabilitiesKHR.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),(MemorySegment)(a3 == null ? MemorySegment.NULL : a3.marshall(arena)));if (a3!=null) a3.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkGetPhysicalDeviceSurfaceFormats2KHR;
  public int vkGetPhysicalDeviceSurfaceFormats2KHR(javaforce.vk.VkPhysicalDevice a1,javaforce.vk.VkPhysicalDeviceSurfaceInfo2KHR a2,int[] a3,javaforce.vk.VkSurfaceFormat2KHR a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a3 = FFM.toMemory(arena, a3);int _ret_value_ = (int)vkGetPhysicalDeviceSurfaceFormats2KHR.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)),_array_a3,(MemorySegment)(a4 == null ? MemorySegment.NULL : a4.marshall(arena)));FFM.copyBack(_array_a3,a3);if (a2!=null) a2.unmarshall();if (a4!=null) a4.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkGetPhysicalDeviceSurfaceFormatsKHR;
  public int vkGetPhysicalDeviceSurfaceFormatsKHR(javaforce.vk.VkPhysicalDevice a1,javaforce.vk.VkSurfaceKHR a2,int[] a3,javaforce.vk.VkSurfaceFormatKHR[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a3 = FFM.toMemory(arena, a3);MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkGetPhysicalDeviceSurfaceFormatsKHR.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),_array_a3,_array_a4);FFM.copyBack(_array_a3,a3);FFM.copyBack(_array_a4,a4);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkGetPhysicalDeviceSurfacePresentModesKHR;
  public int vkGetPhysicalDeviceSurfacePresentModesKHR(javaforce.vk.VkPhysicalDevice a1,javaforce.vk.VkSurfaceKHR a2,int[] a3,javaforce.vk.VkPresentModeKHR[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a3 = FFM.toMemory(arena, a3);MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkGetPhysicalDeviceSurfacePresentModesKHR.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),_array_a3,_array_a4);FFM.copyBack(_array_a3,a3);FFM.copyBack(_array_a4,a4);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkGetPhysicalDeviceSurfaceSupportKHR;
  public int vkGetPhysicalDeviceSurfaceSupportKHR(javaforce.vk.VkPhysicalDevice a1,int a2,javaforce.vk.VkSurfaceKHR a3,int[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkGetPhysicalDeviceSurfaceSupportKHR.invokeExact(a1 == null ? 0 : a1.getValue(),a2,a3 == null ? 0 : a3.getValue(),_array_a4);FFM.copyBack(_array_a4,a4);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkGetSwapchainImagesKHR;
  public int vkGetSwapchainImagesKHR(javaforce.vk.VkDevice a1,javaforce.vk.VkSwapchainKHR a2,int[] a3,javaforce.vk.VkImage[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a3 = FFM.toMemory(arena, a3);MemorySegment _array_a4 = FFM.toMemory(arena, a4);int _ret_value_ = (int)vkGetSwapchainImagesKHR.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),_array_a3,_array_a4);FFM.copyBack(_array_a3,a3);FFM.copyBack(_array_a4,a4);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkMapMemory;
  public int vkMapMemory(javaforce.vk.VkDevice a1,javaforce.vk.VkDevice a2,long a3,long a4,int a5,long[] a6) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a6 = FFM.toMemory(arena, a6);int _ret_value_ = (int)vkMapMemory.invokeExact(a1 == null ? 0 : a1.getValue(),a2 == null ? 0 : a2.getValue(),a3,a4,a5,_array_a6);FFM.copyBack(_array_a6,a6);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkQueuePresentKHR;
  public int vkQueuePresentKHR(javaforce.vk.VkQueue a1,javaforce.vk.VkPresentInfoKHR a2) { try { Arena arena = Arena.ofAuto(); int _ret_value_ = (int)vkQueuePresentKHR.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)));if (a2!=null) a2.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkQueueSubmit;
  public int vkQueueSubmit(javaforce.vk.VkQueue a1,int a2,javaforce.vk.VkSubmitInfo[] a3,javaforce.vk.VkFence a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a3 = FFM.toMemory(arena, a3);int _ret_value_ = (int)vkQueueSubmit.invokeExact(a1 == null ? 0 : a1.getValue(),a2,_array_a3,a4 == null ? 0 : a4.getValue());FFM.copyBack(_array_a3,a3);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkQueueWaitIdle;
  public int vkQueueWaitIdle(javaforce.vk.VkQueue a1) { try { int _ret_value_ = (int)vkQueueWaitIdle.invokeExact(a1 == null ? 0 : a1.getValue());return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkResetCommandBuffer;
  public int vkResetCommandBuffer(javaforce.vk.VkCommandBuffer a1,int a2) { try { int _ret_value_ = (int)vkResetCommandBuffer.invokeExact(a1 == null ? 0 : a1.getValue(),a2);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkResetFences;
  public int vkResetFences(javaforce.vk.VkDevice a1,int a2,javaforce.vk.VkFence[] a3) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a3 = FFM.toMemory(arena, a3);int _ret_value_ = (int)vkResetFences.invokeExact(a1 == null ? 0 : a1.getValue(),a2,_array_a3);FFM.copyBack(_array_a3,a3);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkUpdateDescriptorSets;
  public int vkUpdateDescriptorSets(javaforce.vk.VkDevice a1,int a2,javaforce.vk.VkWriteDescriptorSet a3,int a4,javaforce.vk.VkCopyDescriptorSet a5) { try { Arena arena = Arena.ofAuto(); int _ret_value_ = (int)vkUpdateDescriptorSets.invokeExact(a1 == null ? 0 : a1.getValue(),a2,(MemorySegment)(a3 == null ? MemorySegment.NULL : a3.marshall(arena)),a4,(MemorySegment)(a5 == null ? MemorySegment.NULL : a5.marshall(arena)));if (a3!=null) a3.unmarshall();if (a5!=null) a5.unmarshall();return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkWaitForFences;
  public int vkWaitForFences(javaforce.vk.VkDevice a1,int a2,javaforce.vk.VkFence[] a3,int a4,long a5) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a3 = FFM.toMemory(arena, a3);int _ret_value_ = (int)vkWaitForFences.invokeExact(a1 == null ? 0 : a1.getValue(),a2,_array_a3,a4,a5);FFM.copyBack(_array_a3,a3);return _ret_value_; } catch (Throwable t) { JFLog.log(t);  return -1;} }

  private MethodHandle vkGetDeviceQueue;
  public void vkGetDeviceQueue(javaforce.vk.VkDevice a1,int a2,int a3,javaforce.vk.VkQueue[] a4) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a4 = FFM.toMemory(arena, a4);vkGetDeviceQueue.invokeExact(a1 == null ? 0 : a1.getValue(),a2,a3,_array_a4);FFM.copyBack(_array_a4,a4); } catch (Throwable t) { JFLog.log(t); } }

  private MethodHandle vkGetDeviceQueue2;
  public void vkGetDeviceQueue2(javaforce.vk.VkDevice a1,javaforce.vk.VkDeviceQueueInfo2 a2,javaforce.vk.VkQueue[] a3) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a3 = FFM.toMemory(arena, a3);vkGetDeviceQueue2.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)),_array_a3);FFM.copyBack(_array_a3,a3);if (a2!=null) a2.unmarshall(); } catch (Throwable t) { JFLog.log(t); } }

  private MethodHandle vkGetPhysicalDeviceFeatures2;
  public void vkGetPhysicalDeviceFeatures2(javaforce.vk.VkPhysicalDevice a1,javaforce.vk.VkPhysicalDeviceFeatures2 a2) { try { Arena arena = Arena.ofAuto(); vkGetPhysicalDeviceFeatures2.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)));if (a2!=null) a2.unmarshall(); } catch (Throwable t) { JFLog.log(t); } }

  private MethodHandle vkGetPhysicalDeviceMemoryProperties2;
  public void vkGetPhysicalDeviceMemoryProperties2(javaforce.vk.VkPhysicalDevice a1,javaforce.vk.VkPhysicalDeviceMemoryProperties2 a2) { try { Arena arena = Arena.ofAuto(); vkGetPhysicalDeviceMemoryProperties2.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)));if (a2!=null) a2.unmarshall(); } catch (Throwable t) { JFLog.log(t); } }

  private MethodHandle vkGetPhysicalDeviceProperties2;
  public void vkGetPhysicalDeviceProperties2(javaforce.vk.VkPhysicalDevice a1,javaforce.vk.VkPhysicalDeviceProperties2 a2) { try { Arena arena = Arena.ofAuto(); vkGetPhysicalDeviceProperties2.invokeExact(a1 == null ? 0 : a1.getValue(),(MemorySegment)(a2 == null ? MemorySegment.NULL : a2.marshall(arena)));if (a2!=null) a2.unmarshall(); } catch (Throwable t) { JFLog.log(t); } }

  private MethodHandle vkGetPhysicalDeviceQueueFamilyProperties2;
  public void vkGetPhysicalDeviceQueueFamilyProperties2(javaforce.vk.VkPhysicalDevice a1,int[] a2,javaforce.vk.VkQueueFamilyProperties2[] a3) { try { Arena arena = Arena.ofAuto(); MemorySegment _array_a2 = FFM.toMemory(arena, a2);MemorySegment _array_a3 = FFM.toMemory(arena, a3);vkGetPhysicalDeviceQueueFamilyProperties2.invokeExact(a1 == null ? 0 : a1.getValue(),_array_a2,_array_a3);FFM.copyBack(_array_a2,a2);FFM.copyBack(_array_a3,a3); } catch (Throwable t) { JFLog.log(t); } }


  private boolean ffm_init() {
    if (FFM.debug) JFLog.log("VKFFM init started");
    MethodHandle init;
    ffm = FFM.getInstance();
    Library[] libs = new Library[] {new Library("vulkan")};
    Library.findLibraries(null, libs);
    Arena arena = Arena.ofAuto();
    init = ffm.getFunction("VKinit", ffm.getFunctionDesciptor(ValueLayout.JAVA_BOOLEAN,ADDRESS));
    if (init == null) return false;
    try {if (!(boolean)init.invokeExact(libs[0].getPath(arena))) return false;} catch (Throwable t) {JFLog.log(t); return false;}

    vkAcquireNextImageKHR = ffm.getFunctionPtr("_vkAcquireNextImageKHR", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,JAVA_LONG,JAVA_LONG,JAVA_LONG,ADDRESS));
    vkAllocateCommandBuffers = ffm.getFunctionPtr("_vkAllocateCommandBuffers", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,ADDRESS));
    vkAllocateMemory = ffm.getFunctionPtr("_vkAllocateMemory", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,JAVA_LONG,ADDRESS));
    vkBeginCommandBuffer = ffm.getFunctionPtr("_vkBeginCommandBuffer", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS));
    vkBindBufferMemory = ffm.getFunctionPtr("_vkBindBufferMemory", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,JAVA_LONG,JAVA_LONG));
    vkBindImageMemory = ffm.getFunctionPtr("_vkBindImageMemory", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,JAVA_LONG,JAVA_LONG));
    vkCmdBeginRenderPass = ffm.getFunctionPtr("_vkCmdBeginRenderPass", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,JAVA_INT));
    vkCmdBindDescriptorSets = ffm.getFunctionPtr("_vkCmdBindDescriptorSets", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_INT,JAVA_LONG,JAVA_INT,JAVA_INT,ADDRESS,JAVA_INT,ADDRESS));
    vkCmdBindPipeline = ffm.getFunctionPtr("_vkCmdBindPipeline", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_INT,JAVA_LONG));
    vkCmdBindVertexBuffers = ffm.getFunctionPtr("_vkCmdBindVertexBuffers", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_INT,JAVA_INT,ADDRESS,ADDRESS));
    vkCmdDraw = ffm.getFunctionPtr("_vkCmdDraw", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_INT,JAVA_INT,JAVA_INT,JAVA_INT));
    vkCmdEndRenderPass = ffm.getFunctionPtr("_vkCmdEndRenderPass", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG));
    vkCmdSetScissor = ffm.getFunctionPtr("_vkCmdSetScissor", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_INT,JAVA_INT,ADDRESS));
    vkCmdSetViewport = ffm.getFunctionPtr("_vkCmdSetViewport", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_INT,JAVA_INT,ADDRESS));
    vkCreateBuffer = ffm.getFunctionPtr("_vkCreateBuffer", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,JAVA_LONG,ADDRESS));
    vkCreateCommandPool = ffm.getFunctionPtr("_vkCreateCommandPool", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,JAVA_LONG,ADDRESS));
    vkCreateDescriptorPool = ffm.getFunctionPtr("_vkCreateDescriptorPool", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,JAVA_LONG,ADDRESS));
    vkCreateDescriptorSetLayout = ffm.getFunctionPtr("_vkCreateDescriptorSetLayout", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,JAVA_LONG,ADDRESS));
    vkCreateDevice = ffm.getFunctionPtr("_vkCreateDevice", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,JAVA_LONG,ADDRESS));
    vkCreateFence = ffm.getFunctionPtr("_vkCreateFence", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,JAVA_LONG,ADDRESS));
    vkCreateFramebuffer = ffm.getFunctionPtr("_vkCreateFramebuffer", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,JAVA_LONG,ADDRESS));
    vkCreateGraphicsPipelines = ffm.getFunctionPtr("_vkCreateGraphicsPipelines", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,JAVA_INT,ADDRESS,JAVA_LONG,ADDRESS));
    vkCreateImage = ffm.getFunctionPtr("_vkCreateImage", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,JAVA_LONG,ADDRESS));
    vkCreateImageView = ffm.getFunctionPtr("_vkCreateImageView", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,JAVA_LONG,ADDRESS));
    vkCreateInstance = ffm.getFunctionPtr("_vkCreateInstance", ffm.getFunctionDesciptor(JAVA_INT,ADDRESS,JAVA_LONG,ADDRESS));
    vkCreatePipelineLayout = ffm.getFunctionPtr("_vkCreatePipelineLayout", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,JAVA_LONG,ADDRESS));
    vkCreateRenderPass = ffm.getFunctionPtr("_vkCreateRenderPass", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,JAVA_LONG,ADDRESS));
    vkCreateRenderPass2 = ffm.getFunctionPtr("_vkCreateRenderPass2", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,JAVA_LONG,ADDRESS));
    vkCreateSemaphore = ffm.getFunctionPtr("_vkCreateSemaphore", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,JAVA_LONG,ADDRESS));
    vkCreateShaderModule = ffm.getFunctionPtr("_vkCreateShaderModule", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,JAVA_LONG,ADDRESS));
    vkCreateSwapchainKHR = ffm.getFunctionPtr("_vkCreateSwapchainKHR", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,JAVA_LONG,ADDRESS));
    vkDestroyCommandPool = ffm.getFunctionPtr("_vkDestroyCommandPool", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,JAVA_LONG));
    vkDestroyDevice = ffm.getFunctionPtr("_vkDestroyDevice", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG));
    vkDestroyFence = ffm.getFunctionPtr("_vkDestroyFence", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,JAVA_LONG));
    vkDestroyFramebuffer = ffm.getFunctionPtr("_vkDestroyFramebuffer", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,JAVA_LONG));
    vkDestroyImageView = ffm.getFunctionPtr("_vkDestroyImageView", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,JAVA_LONG));
    vkDestroyInstance = ffm.getFunctionPtr("_vkDestroyInstance", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG));
    vkDestroyPipeline = ffm.getFunctionPtr("_vkDestroyPipeline", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,JAVA_LONG));
    vkDestroyPipelineLayout = ffm.getFunctionPtr("_vkDestroyPipelineLayout", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,JAVA_LONG));
    vkDestroyRenderPass = ffm.getFunctionPtr("_vkDestroyRenderPass", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,JAVA_LONG));
    vkDestroySemaphore = ffm.getFunctionPtr("_vkDestroySemaphore", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,JAVA_LONG));
    vkDestroyShaderModule = ffm.getFunctionPtr("_vkDestroyShaderModule", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,JAVA_LONG));
    vkDestroySurfaceKHR = ffm.getFunctionPtr("_vkDestroySurfaceKHR", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,JAVA_LONG));
    vkDestroySwapchainKHR = ffm.getFunctionPtr("_vkDestroySwapchainKHR", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,JAVA_LONG));
    vkDeviceWaitIdle = ffm.getFunctionPtr("_vkDeviceWaitIdle", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG));
    vkEndCommandBuffer = ffm.getFunctionPtr("_vkEndCommandBuffer", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG));
    vkEnumerateDeviceExtensionProperties = ffm.getFunctionPtr("_vkEnumerateDeviceExtensionProperties", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,ADDRESS,ADDRESS));
    vkEnumeratePhysicalDevices = ffm.getFunctionPtr("_vkEnumeratePhysicalDevices", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,ADDRESS));
    vkFreeCommandBuffers = ffm.getFunctionPtr("_vkFreeCommandBuffers", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,JAVA_INT,ADDRESS));
    vkGetBufferMemoryRequirements = ffm.getFunctionPtr("_vkGetBufferMemoryRequirements", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,ADDRESS));
    vkGetDisplayModePropertiesKHR = ffm.getFunctionPtr("_vkGetDisplayModePropertiesKHR", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,ADDRESS,ADDRESS));
    vkGetDisplayPlaneCapabilitiesKHR = ffm.getFunctionPtr("_vkGetDisplayPlaneCapabilitiesKHR", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,JAVA_INT,ADDRESS));
    vkGetDisplayPlaneSupportedDisplaysKHR = ffm.getFunctionPtr("_vkGetDisplayPlaneSupportedDisplaysKHR", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_INT,ADDRESS,ADDRESS));
    vkGetImageMemoryRequirements = ffm.getFunctionPtr("_vkGetImageMemoryRequirements", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,ADDRESS));
    vkGetPhysicalDeviceDisplayPlanePropertiesKHR = ffm.getFunctionPtr("_vkGetPhysicalDeviceDisplayPlanePropertiesKHR", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,ADDRESS));
    vkGetPhysicalDeviceDisplayPropertiesKHR = ffm.getFunctionPtr("_vkGetPhysicalDeviceDisplayPropertiesKHR", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,ADDRESS));
    vkGetPhysicalDeviceSurfaceCapabilitiesKHR = ffm.getFunctionPtr("_vkGetPhysicalDeviceSurfaceCapabilitiesKHR", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,ADDRESS));
    vkGetPhysicalDeviceSurfaceFormats2KHR = ffm.getFunctionPtr("_vkGetPhysicalDeviceSurfaceFormats2KHR", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS,ADDRESS,ADDRESS));
    vkGetPhysicalDeviceSurfaceFormatsKHR = ffm.getFunctionPtr("_vkGetPhysicalDeviceSurfaceFormatsKHR", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,ADDRESS,ADDRESS));
    vkGetPhysicalDeviceSurfacePresentModesKHR = ffm.getFunctionPtr("_vkGetPhysicalDeviceSurfacePresentModesKHR", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,ADDRESS,ADDRESS));
    vkGetPhysicalDeviceSurfaceSupportKHR = ffm.getFunctionPtr("_vkGetPhysicalDeviceSurfaceSupportKHR", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_INT,JAVA_LONG,ADDRESS));
    vkGetSwapchainImagesKHR = ffm.getFunctionPtr("_vkGetSwapchainImagesKHR", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,ADDRESS,ADDRESS));
    vkMapMemory = ffm.getFunctionPtr("_vkMapMemory", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_LONG,JAVA_LONG,JAVA_LONG,JAVA_INT,ADDRESS));
    vkQueuePresentKHR = ffm.getFunctionPtr("_vkQueuePresentKHR", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,ADDRESS));
    vkQueueSubmit = ffm.getFunctionPtr("_vkQueueSubmit", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_INT,ADDRESS,JAVA_LONG));
    vkQueueWaitIdle = ffm.getFunctionPtr("_vkQueueWaitIdle", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG));
    vkResetCommandBuffer = ffm.getFunctionPtr("_vkResetCommandBuffer", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_INT));
    vkResetFences = ffm.getFunctionPtr("_vkResetFences", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_INT,ADDRESS));
    vkUpdateDescriptorSets = ffm.getFunctionPtr("_vkUpdateDescriptorSets", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_INT,ADDRESS,JAVA_INT,ADDRESS));
    vkWaitForFences = ffm.getFunctionPtr("_vkWaitForFences", ffm.getFunctionDesciptor(JAVA_INT,JAVA_LONG,JAVA_INT,ADDRESS,JAVA_INT,JAVA_LONG));
    vkGetDeviceQueue = ffm.getFunctionPtr("_vkGetDeviceQueue", ffm.getFunctionDesciptorVoid(JAVA_LONG,JAVA_INT,JAVA_INT,ADDRESS));
    vkGetDeviceQueue2 = ffm.getFunctionPtr("_vkGetDeviceQueue2", ffm.getFunctionDesciptorVoid(JAVA_LONG,ADDRESS,ADDRESS));
    vkGetPhysicalDeviceFeatures2 = ffm.getFunctionPtr("_vkGetPhysicalDeviceFeatures2", ffm.getFunctionDesciptorVoid(JAVA_LONG,ADDRESS));
    vkGetPhysicalDeviceMemoryProperties2 = ffm.getFunctionPtr("_vkGetPhysicalDeviceMemoryProperties2", ffm.getFunctionDesciptorVoid(JAVA_LONG,ADDRESS));
    vkGetPhysicalDeviceProperties2 = ffm.getFunctionPtr("_vkGetPhysicalDeviceProperties2", ffm.getFunctionDesciptorVoid(JAVA_LONG,ADDRESS));
    vkGetPhysicalDeviceQueueFamilyProperties2 = ffm.getFunctionPtr("_vkGetPhysicalDeviceQueueFamilyProperties2", ffm.getFunctionDesciptorVoid(JAVA_LONG,ADDRESS,ADDRESS));
    if (FFM.debug) JFLog.log("VKFFM init complete");
    return true;
  }
}
