#!/bin/bash

if [ x$1 = x ]; then
  echo usage : jbus-client package [calls...]
  echo desc : registers as package, make calls, and then prints any calls to this package if any
  echo note : a call to package.exit\(\) will cause this script to end
  exit 0
fi

# Open socket.
exec 3<>/dev/tcp/127.0.0.1/777

# Send msg.
echo Registering as $1
package=$1
echo "cmd.package=$1" >&3

shift
while [ ! "$1" = "" ]; do
  echo "$1" >&3
  shift
done

# Receive msg.
while true; do
  read -r msg <&3
  echo "$msg"
  if [ "$msg" = "$package.exit()" ]; then
    exit
  fi
done
