/**
 *
 * @author pquiring
 *
 * Created : Oct 7, 2013
 */

import javaforce.*;
import javaforce.media.*;

public class VideoApplet extends javax.swing.JApplet {

  /**
   * Initializes the applet VideoApplet
   */
  @Override
  public void init() {
    if (!MediaCoder.init()) {
      if (!MediaCoder.download()) return;
      if (!MediaCoder.init()) return;  //try again after download
    }
    final javax.swing.JApplet applet = this;
    /* Create and display the applet */
    try {
      java.awt.EventQueue.invokeAndWait(new Runnable() {
        public void run() {
          initComponents();
          MainPanel panel = new MainPanel();
          setContentPane(panel);
          Menu.create(applet, panel);
        }
      });
    } catch (Exception ex) {
      ex.printStackTrace();
    }
    JF.loadCerts(getClass().getResourceAsStream("javaforce.crt")
      , getClass().getResourceAsStream("jfvideo.crt"), "jfvideo.sourceforge.net");
  }

  public void destroy() {
    System.exit(0);
  }

  /**
   * This method is called from within the init() method to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
