#!/bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-help" ] ; then
    echo "USAGE: jfvncviewer HOST[:(DISPLAY#|:PORT#)]"
    exit 0
fi

PT=$(echo "$1" | grep "::")
if [ -n "$PT" ] ; then
    HOST=$(echo "$PT" | sed -e "s/::.*//;")
    PORT=$(echo "$PT" | sed -e "s/.*:://;")
else
    PT=$(echo "$1" | grep ":")
    if [ -n "$PT" ] ; then 
	HOST=$(echo "$PT" | sed -e "s/:.*//;")
	P=$(echo "$PT" | sed -e "s/.*://;")
	PORT=$(echo "5900+$P" | bc)
    else
	HOST="$1"
	PORT=5900
    fi
fi

echo $HOST $PORT

export CLASSPATH=/usr/share/java/jfvnc.jar

java VncViewer HOST $HOST PORT $PORT
