#!/bin/bash

# Note : Make sure you place NOPASSWD in your /etc/sudoers or this script will annoy you (see jconfig -> fix stuff)

function usage() {
  echo usage : jfrpm file.spec bits [files.lst]
  echo desc : creates RPM files from file.spec
  echo bits : 32 or 64 bit
  echo note : files.lst is appended to file.spec during process
  exit
}

function error() {
  echo Error : $1
  exit
}

if [ "$1" = "" ]; then usage; fi
if [ "$1" = "--help" ]; then usage; fi
if [ "$1" = "-h" ]; then usage; fi

if [ ! -f $1 ]; then error "$1 not found"; fi

FILES=files.lst
if [ -f files-fedora.lst]; then FILES=files-fedora.lst; fi
BITS=$2
if [ -f files-$BITS.lst]; then FILES=files-$BITS.lst; fi

if [ ! "$3" = "" ]; then FILES=$3; fi

TMPDIR=jfrpm.$RANDOM
SPEC=$1

WORKDIR=`pwd`
mkdir $TMPDIR

#build data.tar.bz2 (gz,bz2,lzma,others?)
rm -f data.tar.bz2 2>/dev/null
tar cjf data.tar.bz2 -T $FILES

cp $SPEC $TMPDIR
cat $FILES >> $TMPDIR/$SPEC
cd $TMPDIR

if [ $BITS = "32" ]; then
  java -jar /usr/share/java/javaforce.jar javaforce.utils.jfr "@ARCH@" "i686" $SPEC
else
  java -jar /usr/share/java/javaforce.jar javaforce.utils.jfr "@ARCH@" "x86_64" $SPEC
fi

if [ ! `pwd` = $WORKDIR/$TMPDIR ]; then error "failed to use temp folder $TMPDIR"; fi

sudo tar xjf ../data.tar.bz2
#NOTE:rpmbuild nukes the buildroot once complete, which is the current folder - be careful!!!
sudo rpmbuild -bb $SPEC --buildroot `pwd`
cd ..
sudo rm -rf $TMPDIR
rm -f data.tar.bz2
sudo chown $USER:$USER *.rpm

echo Complete!
